namespace SuperFluid.Internal.SourceGenerators;

/// <summary>
/// Source for the ambient attribute types that SuperFluid emits into every consuming compilation
/// via <c>RegisterPostInitializationOutput</c>. Consumers never need to reference a runtime package
/// to get these attributes — they exist only at compile time.
/// </summary>
internal static class AttributeDefinitions
{
	public const string Source = """
		// <auto-generated/>
		#nullable enable

		namespace SuperFluid;

		using System;

		[AttributeUsage(AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
		public sealed class FluidApiGrammarAttribute : Attribute { }

		[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
		public sealed class InitialAttribute : Attribute { }

		[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
		public sealed class TransitionsToAttribute : Attribute
		{
			public TransitionsToAttribute(params string[] methodNames) { MethodNames = methodNames; }
			public string[] MethodNames { get; }
		}

		[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
		public sealed class ReturnTypeAttribute : Attribute
		{
			public ReturnTypeAttribute(Type type) { Type = type; }
			public Type Type { get; }
		}

		[AttributeUsage(AttributeTargets.Interface, AllowMultiple = true, Inherited = false)]
		public sealed class StateNameAttribute : Attribute
		{
			public StateNameAttribute(string name, params string[] transitionMethodNames)
			{
				Name = name;
				TransitionMethodNames = transitionMethodNames;
			}
			public string Name { get; }
			public string[] TransitionMethodNames { get; }
		}
		""";
}
